# Generated by Django 5.1.3 on 2024-11-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель')], default='student', max_length=10, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание вебинара'),
        ),
    ]
