# Generated by Django 5.1.3 on 2024-11-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_user_type_alter_webinar_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.profile', verbose_name='Профиль'),
        ),
    ]
